flaskr/views.py
from flask import Blueprint, render_template, request, flash, jsonify, Response
from flask_login import login_required, current_user
from .models import Note, Img
from . import database
import json
import numpy as np
import cv2
import base64
import tensorflow as tf
import pickle
import os
from PIL import Image
import pandas as pd
from werkzeug.utils import secure_filename

views = Blueprint('views', __name__)

init_Base64 = 21
label_dict = {0: 'Cat', 1: 'Giraffe', 2: 'Sheep',
              3: 'Bat', 4: 'Octopus', 5: 'Camel'}
graph = tf.get_default_graph()

enviroment = 'production'

if enviroment == 'development':
    path = f'flaskr\model_cnn.pkl'
elif enviroment == 'production':
    path = f'/app/flaskr/model_cnn.pkl'

with open(path, 'rb') as f:
    model = pickle.load(f)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if Img.query.filter_by(user_id=current_user.id).first():
        # print(Img.query.filter_by(user_id=current_user.id))
        # img = Img.query.filter_by(user_id=current_user.id)
        # drawing = img.img
        # drawing_name = img.name

        img_list = Img.query.filter_by(user_id=current_user.id).all()

        return render_template("home.html", img_list=img_list, user=current_user)
    else:
        return render_template("home.html", user=current_user)


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            database.session.delete(note)
            database.session.commit()

    return jsonify({})


@views.route('/predict', methods=['POST'])
def predict():
    global graph
    with graph.as_default():
        if request.method == 'POST':
            final_pred = None
            draw = request.form['url']
            drawing = draw
            draw = draw[init_Base64:]
            draw_decoded = base64.b64decode(draw)
            image = np.asarray(bytearray(draw_decoded), dtype="uint8")
            image = cv2.imdecode(image, cv2.IMREAD_GRAYSCALE)
            # height = image.shape[0]
            # width = image.shape[1]
            # background = np.zeros([width, width, 3], dtype=np.uint8)
            # background.fill(0)
            # background = Image.fromarray(background)
            # background.paste(Image.fromarray(image),
            #                  (0, (int((width-height)/2))))
            # pil_image = background.convert('RGB')
            # open_cv_image = np.array(pil_image)
            # open_cv_image = open_cv_image[:, :, 0].copy()
            # resized = cv2.resize(open_cv_image, (28, 28),
            #                      interpolation=cv2.INTER_AREA)
            resized = cv2.resize(image, (28, 28), interpolation=cv2.INTER_AREA)
            vect = np.asarray(resized, dtype="uint8")
            vect = vect.reshape(1, 1, 28, 28).astype('float32')
            my_prediction = model.predict(vect)
            index = np.argmax(my_prediction[0])
            final_pred = label_dict[index]

    return render_template('results.html', prediction=final_pred, drawing=drawing, user=current_user)


@views.route('/draw', methods=['POST'])
def draw():
    if request.method == 'POST':
        if request.form.get('dict') == "Cat":
            dict = "gato"
        elif request.form.get('dict') == "Giraffe":
            dict = "girafa"
        elif request.form.get('dict') == "Sheep":
            dict = "ovelha"
        elif request.form.get('dict') == "Bat":
            dict = "morcego"
        elif request.form.get('dict') == "Octopus":
            dict = "polvo"
        elif request.form.get('dict') == "Camel":
            dict = "camelo"
    return render_template('draw.html', user=current_user, dict=dict)


@views.route('/grading', methods=['POST'])
def grading():
    global graph
    with graph.as_default():
        if request.method == 'POST':
            draw = request.form['url']
            drawing = draw
            draw = draw[init_Base64:]
            draw_decoded = base64.b64decode(draw)
            image = np.asarray(bytearray(draw_decoded), dtype="uint8")
            image = cv2.imdecode(image, cv2.IMREAD_GRAYSCALE)
            # height = image.shape[0]
            # width = image.shape[1]
            # background = np.zeros([width, width, 3], dtype=np.uint8)
            # background.fill(0)
            # background = Image.fromarray(background)
            # background.paste(Image.fromarray(image),
            #                  (0, (int((width-height)/2))))
            # pil_image = background.convert('RGB')
            # open_cv_image = np.array(pil_image)
            # open_cv_image = open_cv_image[:, :, 0].copy()
            # resized = cv2.resize(open_cv_image, (28, 28),
            #                      interpolation=cv2.INTER_AREA)
            resized = cv2.resize(image, (28, 28), interpolation=cv2.INTER_AREA)
            vect = np.asarray(resized, dtype="uint8")
            vect = vect.reshape(1, 1, 28, 28).astype('float32')
            my_prediction = model.predict(vect)
            df = pd.DataFrame(my_prediction)
            dict = request.form.get('dict')
            if dict == "gato":
                index = 0
                pronoun = 'Seu'
            elif dict == "girafa":
                index = 1
                pronoun = 'Sua'
            elif dict == "ovelha":
                index = 2
                pronoun = 'Sua'
            elif dict == "morcego":
                index = 3
                pronoun = 'Seu'
            elif dict == "polvo":
                index = 4
                pronoun = 'Seu'
            elif dict == "camelo":
                index = 5
                pronoun = 'Seu'
            value = df[index].values[0]
            grading = int(value * 10)
            message = pronoun + ' ' + dict + \
                ' ficou  nota ' + str(grading) + '!'
    return render_template('grading.html', dict=dict, message=message, drawing=drawing, user=current_user)


@views.route('/save', methods=['POST'])
def save():
    global graph
    with graph.as_default():
        if request.method == 'POST':
            global message
            final_pred = request.form.get('prediction')
            message = request.form.get('message')
            dict = request.form.get('dict')
            drawing = request.form['drawing']
            drawing_name = request.form.get('drawing_name')

            # if not pic:
            #     return 'No pic uploaded!', 400

            # filename = secure_filename(pic.filename)
            # mimetype = pic.mimetype
            # if not filename or not mimetype:
            #     return 'Bad upload!', 400

            img = Img(img=drawing,
                      name=drawing_name, user_id=current_user.id)
            database.session.add(img)
            database.session.commit()

            if dict == "gato":
                flash('O gato foi salvo!', category='success')
                return render_template('grading.html', dict=dict,
                                       message=message, drawing=drawing, user=current_user)
            elif dict == "girafa":
                flash('A girafa foi salva!', category='success')
                return render_template('grading.html', dict=dict,
                                       message=message, drawing=drawing, user=current_user)
            elif dict == "ovelha":
                flash('A ovelha foi salva!', category='success')
                return render_template('grading.html', dict=dict,
                                       message=message, drawing=drawing, user=current_user)
            elif dict == "morcego":
                flash('O morcego foi salvo!', category='success')
                return render_template('grading.html', dict=dict,
                                       message=message, drawing=drawing, user=current_user)
            elif dict == "polvo":
                flash('O polvo foi salvo!', category='success')
                return render_template('grading.html', dict=dict,
                                       message=message, drawing=drawing, user=current_user)
            elif dict == "camelo":
                flash('O camelo foi salvo!', category='success')
                return render_template('grading.html', dict=dict,
                                       message=message, drawing=drawing, user=current_user)
            else:
                flash('O desenho foi salvo!', category='success')
    return render_template('results.html', prediction=final_pred, drawing=drawing, user=current_user)


@views.route('/<int:id>')
def get_img(id):
    img = Img.query.filter_by(id=id).first()
    if not img:
        return 'Img Not Found!', 404

    return Response(img.img, mimetype=img.mimetype)

flaskr/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}Ho Hey</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheet.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='jquery.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='draw.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
</head>

<body>

    <!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-wide w3-padding" style="border-bottom: 5px solid lightgrey;">
            <a href="/#home" class="w3-bar-item w3-button"><b>Ho</b> Hey</a>
            <!-- Float links to the right. Hide them on small screens -->
            <div class="w3-right w3-hide-small">
                {% if user.is_authenticated %}
                <a href="/#draw" class="w3-bar-item w3-button">Desenhar</a>
                <a href="/#my-drawings" class="w3-bar-item w3-button">Meus desenhos</a>
                <a href="/#about" class="w3-bar-item w3-button">Sobre</a>
                <a href="/#contact" class="w3-bar-item w3-button">Contato</a>
                <a href="/logout" class="w3-bar-item w3-button">Sair</a>
                {% else %}
                <a href="/register" class="w3-bar-item w3-button">Inscrever-se</a>
                <a href="/login" class="w3-bar-item w3-button">Entrar</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% block content %}{% endblock %}

    <div class="w3-content w3-padding" style="max-width:1564px">
        <div class="w3-container">
            {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message
            in
            messages %} {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %} {% endfor %} {% endif %} {% endwith %}
        </div>
    </div>

    <!-- Footer -->
    <footer class="w3-center w3-black w3-padding-16">
        <p>Distribuído pelo Grupo de Pesquisa e Desenvolvimento de Jogos do <a
                href="https://www.udc.edu.br/site/#/udc/instituicao/1" target="_blank" class="w3-hover-text-blue">Centro
                Universitário Dinâmica das Cataratas</a></p>
    </footer>

</body>

</html>

flaskr/templates/draw.html
{% extends "base.html" %}
{% block title %}Desenhar {{ dict }} – {% endblock %}

{% block content %}
<header class="w3-display-container w3-wide" style="max-width:1500px;">
    <form action="{{ url_for('views.grading') }}" method="POST" enctype="multipart/form-data">
        <canvas id="canvas" , width="800" height="800" , style="
                padding-left: 0;
                padding-right: 0;
                margin-left: auto;
                margin-right: auto;
                display: block;
                width: 800px;
                outline: 5px solid lightgrey;">
            <script type="text/javascript">
                $(document).ready(function () {
                    // function clearRect() {
                    //     const canvas = document.getElementById('canvas'),
                    //         context = canvas.getContext('2d');
                    //     context.clearRect(0, 0, context.canvas.width, context.canvas.height);
                    // }
                    drawCanvas();
                })();
            </script>
        </canvas>
    </form>
</header>

<div class="w3-content w3-padding" style="max-width:1564px">
    <div class="w3-row-padding w3-grayscale w3-padding-16">
        <form class="w3-col l3 m6 w3-margin-bottom" action="{{ url_for('views.grading') }}" method="POST"
            enctype="multipart/form-data">
            <input type="hidden" id='url' name="url" value="">
            <input type="hidden" name="dict" value="{{ dict }}">
            <div>
                <input class="w3-button w3-light-grey w3-block" type="submit" value="Avaliar {{ dict }}"
                    onclick="return save();">
            </div>
        </form>
        <!-- <form class="w3-col l3 m6 w3-margin-bottom">
            <input class="w3-button w3-light-grey w3-block" value="Limpar" onclick="return clearRect();">
        </form> -->
    </div>
</div>
{% endblock %}

flaskr/templates/grading.html
{% extends "base.html" %}
{% block title %}Avaliar {{ dict }} – {% endblock %}

{% block content %}
<div class="w3-content w3-padding" style="max-width:1564px">
    <div class="w3-container w3-padding-32">
        <h3 class="w3-padding-16">{{ message }}</h3>
        <img src="{{ drawing }}" style="width:60%">
        <br>
        <form class="w3-col l3 m6 w3-margin-bottom w3-padding-32" action="{{ url_for('views.save') }}" method="POST"
            enctype="multipart/form-data">
            <input type="hidden" id='dict' name="dict" value="{{ dict }}">
            <input type="hidden" id='message' name="message" value="{{ message }}">
            <input type="hidden" id='drawing' name="drawing" value="{{ drawing }}">
            <input class="w3-input w3-border" type="text" placeholder="Dê um nome" required name="drawing_name">
            <button class="w3-button w3-black w3-section" type="submit">
                <i class="fa fa-paper-plane"></i> SALVAR {{ dict.upper() }}
            </button>
        </form>
        </form>
    </div>
</div>
{% endblock %}

flaskr/templates/home.html
{% extends "base.html" %}
{% block title %}{% endblock %}

{% block content %}

<!-- Header -->
<header class="w3-display-container w3-wide" style="max-width:1500px;" id="home">

    <form action="{{ url_for('views.predict')}}" method="POST" enctype="multipart/form-data">
        
        <canvas id="canvas" , width="800" height="800" , style="
                padding-left: 0;
                padding-right: 0;
                margin-left: auto;
                margin-right: auto;
                display: block;
                width: 800px;
                outline: 5px solid lightgrey;">
            <script type="text/javascript">
                $(document).ready(function () {
                    // var canvas = document.getElementById('canvas'),
                    //     context = canvas.getContext('2d');

                    // window.addEventListener('resize', resizeCanvas, false);

                    // function resizeCanvas() {
                    //     canvas.width = window.innerWidth;
                    //     canvas.height = window.innerHeight;
                    drawCanvas();
                    //     redraw();
                    // }
                    // resizeCanvas();
                })();
            </script>
        </canvas>
    </form>

</header>

<!-- Page content -->
<div class="w3-content w3-padding" style="max-width:1564px">

    <div class="w3-row-padding w3-grayscale w3-padding-16">
        <form class="w3-col l3 m6 w3-margin-bottom" action="{{ url_for('views.predict') }}" method="POST"
            enctype="multipart/form-data">
            <input type="hidden" id='url' name="url" value="">
            <div>
                <input class="w3-button w3-light-grey w3-block" type="submit" value="Descobrir" onclick="return save();">
            </div>
        </form>
        <form class="w3-col l3 m6 w3-margin-bottom" action="{{ url_for('views.home') }}" method="POST"
            enctype="multipart/form-data">
            <input type="hidden" id='url' name="url" value="">
            <div>
                <input class="w3-button w3-light-grey w3-block" type="submit" value="Limpar">
            </div>
        </form>
    </div>

    <div class="w3-container w3-padding-32" id="draw">
        <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Teste suas habilidades!</h3>
    </div>

    <form action="/draw" method="POST">
        <div class="w3-row-padding w3-grayscale">
            <div class="w3-col l3 m6 w3-margin-bottom">
                <img src="{{ url_for('static', filename='cat.png') }}" alt="Cat" style="width:50%">
                <h3>Gato</h3>
                <p class="w3-opacity">Animal</p>
                <p>O gato é um mamífero carnívoro da família dos felídeos, muito popular como animal de estimação.</p>
                <p><button class="w3-button w3-light-grey w3-block" type="submit" value="Cat"
                        name="dict">Desenhar</button>
                </p>
            </div>
            <div class="w3-col l3 m6 w3-margin-bottom">
                <img src="{{ url_for('static', filename='giraffe.png') }}" alt="Giraffe" style="width:50%">
                <h3>Girafa</h3>
                <p class="w3-opacity">Animal</p>
                <p>A girafa é um mamífero artiodátilo, ruminante, do gênero Giraffa, da família dos girafídeos.</p>
                <p><button class="w3-button w3-light-grey w3-block" type="submit" value="Giraffe"
                        name="dict">Desenhar</button></p>
            </div>
            <div class="w3-col l3 m6 w3-margin-bottom">
                <img src="{{ url_for('static', filename='sheep.png') }}" alt="Sheep" style="width:50%">
                <h3>Ovelha</h3>
                <p class="w3-opacity">Animal</p>
                <p>A ovelha é um quadrúpede, mamífero ruminante normalmente mantido para criação.</p>
                <p><button class="w3-button w3-light-grey w3-block" type="submit" value="Sheep"
                        name="dict">Desenhar</button></p>
            </div>
            <div class="w3-col l3 m6 w3-margin-bottom">
                <img src="{{ url_for('static', filename='bat.png') }}" alt="Bat" style="width:50%">
                <h3>Morcego</h3>
                <p class="w3-opacity">Animal</p>
                <p>O morcego é um mamífero da ordem Chiroptera, cujos integrantes apresentam uma fina membrana de pele
                    entre os dedos, a qual se estende até as patas e se conecta às laterais do corpo, formando as asas.
                </p>
                <p><button class="w3-button w3-light-grey w3-block" type="submit" value="Bat"
                        name="dict">Desenhar</button></p>
            </div>
            <div class="w3-col l3 m6 w3-margin-bottom">
                <img src="{{ url_for('static', filename='octopus.png') }}" alt="Octopus" style="width:50%">
                <h3>Polvo</h3>
                <p class="w3-opacity">Animal</p>
                <p>O polvos é um molusco marinho da classe Cephalopoda, da ordem Octopoda, possuindo oito braços fortes
                    à volta da boca.</p>
                <p><button class="w3-button w3-light-grey w3-block" type="submit" value="Octopus"
                        name="dict">Desenhar</button></p>
            </div>
            <div class="w3-col l3 m6 w3-margin-bottom">
                <img src="{{ url_for('static', filename='camel.png') }}" alt="Camel" style="width:50%">
                <h3>Camelo</h3>
                <p class="w3-opacity">Animal</p>
                <p>O camelo é um gênero de ungulados artiodáctilos (com um par de dedos de apoio em cada pata) que
                    contém duas espécies: o dromedário, de uma corcova, e o bactriano, de duas corcovas.</p>
                <p><button class="w3-button w3-light-grey w3-block" type="submit" value="Camel"
                        name="dict">Desenhar</button></p>
            </div>
        </div>
    </form>

    <div class="w3-container w3-padding-32" id="my-drawings">
        <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Meus desenhos</h3>
    </div>

    <div class="w3-row-padding">
        {% for img in img_list %}
        <div class="w3-col l3 m6 w3-margin-bottom">
            <div class="w3-display-container">
                <div class="w3-display-topleft w3-black w3-padding">{{ img.name }}</div>
                <img src="{{ img.img }}" style="width:100%">
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- About Section -->
    <div class="w3-container w3-padding-32" id="about">
        <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Sobre</h3>
        <p>Esta página é parte de um protótipo desenvolvido em âmbito acadêmico que utiliza conceitos práticos de Redes
            Neurais Convolucionais para classificar imagens. Alguns artefatos do conjunto de dados da ferramenta 'Quick,
            draw!', desenvolvida pelo Google, foram utilizados para treinar este modelo.</p>
    </div>

    <!-- Contact Section -->
    <div class="w3-container w3-padding-32" id="contact">
        <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Contato</h3>
        <!-- <p>Lets get in touch and talk about your next project.</p> -->
        <p>Vamos entrar em contato e conversar sobre sua sugestão.</p>
        <form action="/action_page.php" target="_blank">
            <input class="w3-input w3-border" type="text" placeholder="Nome" required name="Name">
            <input class="w3-input w3-section w3-border" type="text" placeholder="E-mail" required name="Email">
            <input class="w3-input w3-section w3-border" type="text" placeholder="Assunto" required name="Subject">
            <input class="w3-input w3-section w3-border" type="text" placeholder="Comente" required name="Comment">
            <button class="w3-button w3-black w3-section" type="submit">
                <i class="fa fa-paper-plane"></i> ENVIAR MENSAGEM
            </button>
        </form>
    </div>

    <!-- Image of location/map -->
    <!-- <div class="w3-container">
            <img src="/w3images/map.jpg" class="w3-image" style="width:100%">
        </div> -->

    <!-- End page content -->
</div>

{% endblock %}

flaskr/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}

{% block content %}
<form method="POST">
  <h3 align="center">Register</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

flaskr/templates/results.html
{% extends "base.html" %}
{% block title %}Descoberta – {% endblock %}

{% block content %}
<div class="w3-content w3-padding" style="max-width:1564px">
    <div class="w3-container w3-padding-32">
        {% if prediction == "Cat" %}
        <h3 class="w3-padding-16">Parece um gato!</h3>
        {% elif prediction == "Giraffe" %}
        <h3 class="w3-padding-16">Parece uma girafa!</h3>
        {% elif prediction == "Sheep" %}
        <h3 class="w3-padding-16">Parece uma ovelha!</h3>
        {% elif prediction == "Bat" %}
        <h3 class="w3-padding-16">Parece um morcego!</h3>
        {% elif prediction == "Octopus" %}
        <h3 class="w3-padding-16">Parece um polvo!</h3>
        {% elif prediction == "Camel" %}
        <h3 class="w3-padding-16">Parece um camelo!</h3>
        {% else %}
        <h3 class="w3-padding-16">Nada para descobrir!</h3>
        {% endif %}
        <img src="{{ drawing }}" style="width:60%">
        <br>
        <form class="w3-col l3 m6 w3-margin-bottom w3-padding-32" action="{{ url_for('views.save') }}" method="POST"
            enctype="multipart/form-data">
            <input type="hidden" id='prediction' name="prediction" value="{{ prediction }}">
            <input type="hidden" id='drawing' name="drawing" value="{{ drawing }}">
            <input class="w3-input w3-border" type="text" placeholder="Dê um nome" required name="drawing_name">
            <button class="w3-button w3-black w3-section" type="submit">
                <i class="fa fa-paper-plane"></i> SALVAR DESENHO
            </button>
        </form>
    </div>
</div>
{% endblock %}

flaskr/templates/save.html
{% extends "base.html" %}
{% block title %}Salvar {{ dict }} – {% endblock %}

{% block content %}
<div class="w3-content w3-padding" style="max-width:1564px">
    <div class="w3-container w3-padding-32">
        <div>
            <h3 class="w3-padding-16">{{ message }}</h3>
            <img src="{{ drawing }}" style="width:100%">
        </div>
    </div>
</div>
{% endblock %}